= springboot-elasticsearch-thymeleaf

== Goal

The goal of this project is to implement two services: `product-api` and `product-ui`.
`product-api` is a Restful Web Service that manages products. It uses https://www.elastic.co[Elasticsearch] as storage.
`product-ui` is an UI application that consumes `product-api`. It uses https://www.thymeleaf.org/[Thymeleaf] as HTML template.

== Start Environment

==== Docker Compose

- Open one terminal

- In `/springboot-elasticsearch-thymeleaf` root folder run
----
docker-compose up -d
----

[NOTE]
====
To stop and remove containers, networks, images, and volumes
```
docker-compose down -v
```
====

- Wait a little bit to docker containers be up and healthy. To check it, run
----
docker-compose ps
----

== product-api

Please, refer to `product-api` documentation in order to get more information about how to start and use it.

== product-ui

Please, refer to `product-ui` documentation in order to get more information about how to start and use it.