= springboot-elasticsearch-thymeleaf

== Goal

The goal of this project is to implement two services: `product-api` and `product-ui`.
`product-api` is a Restful Web Service that manages products. It uses https://www.elastic.co[Elasticsearch] as storage.
`product-ui` is a `product-api` UI client. It uses https://www.thymeleaf.org/[Thymeleaf] as HTML template.

== Start Environment

- Open one terminal

- In `/springboot-elasticsearch-thymeleaf` root folder run
```
docker-compose up -d
```

[NOTE]
====
To stop and remove containers, networks, images, and volumes
```
docker-compose down -v
```
====

- Wait a little bit to docker containers be up and healthy. To check it, run
```
docker-compose ps
```

== Configure index, alias and insert some products in ES

- Go to `/springboot-elasticsearch-thymeleaf/scripts` folder

- Run the following script to create the index `ecommerce_v1` with the alias `ecommerce`
```
./create-index.sh
```

- If you want to insert some products, run
```
./insert-products.sh
```

- If you want to fix the `reference` property mapping error (explained bellow), run
```
./reindex.sh
```

===== Reindex

The script `./reindex.sh` is used to reindex from an index to another index. The default will reindex from `ecommerce_v1`
to `ecommerce_v2`. The only difference between `mapping-v1.json` (used by `ecommerce_v1`) to `mapping-v2.json` (used by
`ecommerce_v2`) is the `type` of the `reference` property. In the former is set `text` and in the latter, `keyword`.

It is interesting because, the `reference` property has some special characters. An example of `reference` code is
`SBES@DDR4-10000`. As it is a `text`, ES (using the `standard` analyzer) splits the content in tokens ['SBES', 'DDR4',
10000]. So, for example, if you are looking for a product with `DDR4` RAM and, for some reason, the string `DDR4` is
present in the reference code of some product X, the product X will be selected, even if it doesn't have `DDR4` in its
description. It is an error.

So, the script `./reindex.sh` aims to fix it, setting the type `keyword` to `reference` property. The `DDR4` problem
won't happen again because, from now on, ES won't tokenize the content present in the `reference` property.

== eureka-server

==== Start eureka-server using Maven

In `/springboot-elasticsearch-thymeleaf/eureka-server` root folder run
```
mvn spring-boot:run
```

== product-api

==== Start product-api using Maven

In `/springboot-elasticsearch-thymeleaf/product-api` root folder run
```
mvn spring-boot:run
```

==== Using product-api Swagger

You can access the Swagger website http://localhost:8080/swagger-ui.html to have access to all endpoints.

== product-ui

==== Start product-ui using Maven

In `/springboot-elasticsearch-thymeleaf/product-ui` root folder run
```
mvn spring-boot:run
```

==== Using product-ui

Just access http://localhost:8081

== Elasticsearch REST API

- Alias: `ecommerce`
- Index: `ecommerce_v1`
- New Index: `ecommerce_v2`
- Type: `product`
- REST API Format: `http://host:port/index/type/_action-OR-id`

==== Check ES is up and running
```
curl http://localhost:9200
```

==== Create _ecommerce_v1_ index
```
curl -X PUT localhost:9200/ecommerce_v1 \
     -H "Content-Type: application/json" \
     -d '{ "mappings": { "product": { "properties": { "name": { "type": "text" }, ... }'
```

==== Check indexes in ES
```
curl http://localhost:9200/_cat/indices?v
```

==== Check _ecommerce_v1_ index mapping
```
curl http://localhost:9200/ecommerce_v1/_mapping
```

==== Delete _ecommerce_v1_ index
```
curl -X DELETE http://localhost:9200/ecommerce_v1
```

==== Create alias for _ecommerce_v1_ index
```
curl -X POST localhost:9200/_aliases \
     -H 'Content-Type: application/json' \
     -d '{ "actions": [{ "add": {"alias": "ecommerce", "index": "ecommerce_v1" }}]}'
```

==== Check existing ES alias
```
curl http://localhost:9200/_aliases
```

==== Reindex from _ecommerce_v1_ to _ecommerce_v2_
```
curl -X POST localhost:9200/_reindex \
     -H 'Content-Type: application/json' \
     -d '{ "source": { "index": "ecommerce_v1" }, "dest": { "index": "ecommerce_v2" }}'
```

==== Adjust alias after reindex from _ecommerce_v1_ to _ecommerce_v2_
```
curl -X POST localhost:9200/_aliases \
     -H 'Content-Type: application/json' \
     -d '{ "actions": [{ "remove": {"alias": "ecommerce", "index": "ecommerce_v1" }}, { "add": {"alias": "ecommerce", "index": "ecommerce_v2" }}]}'
```

==== Simple search
```
curl http://localhost:9200/ecommerce/product/_search
```

== TODO

- add same nav bar to all pages & add home button;
- add pagination. now, it is just returning all products;
- add functionality to delete products;

== Reference

https://www.baeldung.com/spring-cloud-netflix-eureka
https://dzone.com/articles/microservice-architecture-with-spring-cloud-and-do
https://www.digit.in/laptops-reviews